//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AssessmentQuestion
    {
        public int QuestionID { get; set; }
        public Nullable<int> AssessmentID { get; set; }
        public string QuestionText { get; set; }
    
        public virtual Assessment Assessment { get; set; }
    }
}
