//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BadgeConfig
    {
        public int BadgeId { get; set; }
        public string BadgeType { get; set; }
        public string Description { get; set; }
        public string ConditionType { get; set; }
        public int RequiredCount { get; set; }
        public string IconPath { get; set; }
    }
}
