//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmergencyContact
    {
        public int Id { get; set; }
        public string Country { get; set; }
        public string OrganizationName { get; set; }
        public string PhoneNumber { get; set; }
        public string Website { get; set; }
        public string Notes { get; set; }
    }
}
