//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HomeworkSubmission
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HomeworkSubmission()
        {
            this.TherapistFeedbacks = new HashSet<TherapistFeedback>();
        }
    
        public int SubmissionId { get; set; }
        public int HomeworkId { get; set; }
        public int UserId { get; set; }
        public string TextResponse { get; set; }
        public string AudioPath { get; set; }
        public string ImagePath { get; set; }
        public Nullable<System.DateTime> SubmittedDate { get; set; }
    
        public virtual TherapeuticHomework TherapeuticHomework { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TherapistFeedback> TherapistFeedbacks { get; set; }
    }
}
