//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mindhavenDBEntities1 : DbContext
    {
        public mindhavenDBEntities1()
            : base("name=mindhavenDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Announcement> Announcements { get; set; }
        public virtual DbSet<Appointment> Appointments { get; set; }
        public virtual DbSet<Article> Articles { get; set; }
        public virtual DbSet<AssessmentQuestion> AssessmentQuestions { get; set; }
        public virtual DbSet<AssessmentResult> AssessmentResults { get; set; }
        public virtual DbSet<Assessment> Assessments { get; set; }
        public virtual DbSet<BadgeConfig> BadgeConfigs { get; set; }
        public virtual DbSet<CaseStudy> CaseStudies { get; set; }
        public virtual DbSet<CustomActivity> CustomActivities { get; set; }
        public virtual DbSet<DeleteRequest> DeleteRequests { get; set; }
        public virtual DbSet<EmergencyContact> EmergencyContacts { get; set; }
        public virtual DbSet<Feedback> Feedbacks { get; set; }
        public virtual DbSet<GroupPost> GroupPosts { get; set; }
        public virtual DbSet<HomeworkSubmission> HomeworkSubmissions { get; set; }
        public virtual DbSet<JournalEntry> JournalEntries { get; set; }
        public virtual DbSet<MediaMention> MediaMentions { get; set; }
        public virtual DbSet<MeditationDeleteRequest> MeditationDeleteRequests { get; set; }
        public virtual DbSet<Meditation> Meditations { get; set; }
        public virtual DbSet<MoodLog> MoodLogs { get; set; }
        public virtual DbSet<MoodReminder> MoodReminders { get; set; }
        public virtual DbSet<Note> Notes { get; set; }
        public virtual DbSet<Resource> Resources { get; set; }
        public virtual DbSet<Resource1> Resources1 { get; set; }
        public virtual DbSet<SelfCareActivity> SelfCareActivities { get; set; }
        public virtual DbSet<SharedAccess> SharedAccesses { get; set; }
        public virtual DbSet<Subscriber> Subscribers { get; set; }
        public virtual DbSet<SupportGroup> SupportGroups { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Tag> Tags { get; set; }
        public virtual DbSet<TherapeuticHomework> TherapeuticHomeworks { get; set; }
        public virtual DbSet<TherapistFeedback> TherapistFeedbacks { get; set; }
        public virtual DbSet<Therapist> Therapists { get; set; }
        public virtual DbSet<UserAchievement> UserAchievements { get; set; }
        public virtual DbSet<UserActivity> UserActivities { get; set; }
        public virtual DbSet<UserActivityLog> UserActivityLogs { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserSetting> UserSettings { get; set; }
        public virtual DbSet<Achievement> Achievements { get; set; }
    }
}
