//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoodLog
    {
        public int MoodID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> MoodLevel { get; set; }
        public string MoodNote { get; set; }
        public string MoodTag { get; set; }
        public Nullable<System.DateTime> LoggedAt { get; set; }
        public Nullable<int> CareTeamMemberId { get; set; }
        public Nullable<bool> IsShared { get; set; }
        public Nullable<bool> ShareWithCareTeam { get; set; }
        public string CareTeamMember { get; set; }
    
        public virtual User User { get; set; }
    }
}
