//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Resource1
    {
        public int ResourceID { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
        public string MediaType { get; set; }
        public string Link { get; set; }
    }
}
