//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Therapist
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Therapist()
        {
            this.Appointments = new HashSet<Appointment>();
        }
    
        public int TherapistID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string Bio { get; set; }
        public string Specialization { get; set; }
        public string AvailableSlots { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Appointment> Appointments { get; set; }
        public virtual User User { get; set; }
    }
}
