//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TherapistFeedback
    {
        public int FeedbackId { get; set; }
        public int SubmissionId { get; set; }
        public int TherapistId { get; set; }
        public string Notes { get; set; }
        public Nullable<System.DateTime> FeedbackDate { get; set; }
    
        public virtual HomeworkSubmission HomeworkSubmission { get; set; }
        public virtual User User { get; set; }
    }
}
