//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSetting
    {
        public int UserId { get; set; }
        public Nullable<bool> ShowNotifications { get; set; }
        public Nullable<bool> EnableChat { get; set; }
        public Nullable<bool> ShowHistory { get; set; }
        public Nullable<bool> OfflineStatus { get; set; }
    }
}
