//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserActivityLog
    {
        public int LogId { get; set; }
        public int UserId { get; set; }
        public int ActivityId { get; set; }
        public System.DateTime CompletedAt { get; set; }
        public string Notes { get; set; }
    
        public virtual SelfCareActivity SelfCareActivity { get; set; }
        public virtual User User { get; set; }
    }
}
