//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mindhaven.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAchievement
    {
        public int AchievementId { get; set; }
        public int UserID { get; set; }
        public string BadgeType { get; set; }
        public Nullable<System.DateTime> DateEarned { get; set; }
        public Nullable<int> Progress { get; set; }
    
        public virtual User User { get; set; }
        public virtual Achievement Achievement { get; set; }
    }
}
